export interface ThicknessVariant {
  thickness: string;
  thickness_cm: number;
  slug: string;
  priceValue: number;
  price: string;
  originalPrice: number;
  sqftPrice: number;
  warranty: number;
  warranty_years: number;
  badge: string;
  badgeColor: string;
  subtitle: string;
  description: string;
  image: string;
  images: string[];
}

export interface CatalogProduct {
  id: number;
  slug: string;
  title: string;
  name: string;
  subtitle: string;
  type: string;
  category: string;
  firmness: string;
  thickness: string;
  thickness_cm: number;
  sqftPrice: number;
  warranty: number;
  warranty_years: number;
  priceValue: number;
  price: string;
  originalPrice: number;
  rating: number;
  reviews: number;
  badge: string;
  badgeColor: string;
  description: string;
  benefits: string[];
  image: string;
  images: string[];
  variants: {
    size: string;
    dimensions: string;
    thickness_cm: number;
    price: number;
    mrp: number;
    stock: number;
    sku: string;
  }[];
  status: string;
  /** If set, this card groups multiple thickness options — shown as one card */
  thicknessVariants?: ThicknessVariant[];
}

export const PRODUCT_CATALOG: CatalogProduct[] = [
  {
    id: 1,
    slug: 'mona-softy',
    title: 'Mona Softy',
    name: 'Mona Softy',
    subtitle: 'Plush Comfort Budget Mattress',
    type: 'Orthopaedic',
    category: 'orthopaedic',
    firmness: 'Medium Firm',
    thickness: '6 Inch',
    thickness_cm: 15,
    sqftPrice: 528,
    warranty: 5,
    warranty_years: 5,
    priceValue: 9504,
    price: '₹9,504',
    originalPrice: 12355,
    rating: 4.7,
    reviews: 1620,
    badge: 'POPULAR',
    badgeColor: 'bg-[#8b5cf6] text-white',
    description: 'Soft, breathable comfort layer designed for daily rest and relaxation at an unbeatable budget price.',
    benefits: ['Plush Cloud Feel', 'Pressure Relief', 'Budget Friendly'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309266/file_sikimv.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309266/file_sikimv.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309266/file_sikimv.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309266/file_sikimv.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 15, price: 9504, mrp: 12355, stock: 20, sku: 'MONS-6-S' }],
    status: 'active'
  },
  {
    id: 2,
    slug: 'ecolatex-6',
    title: 'Eco Latex',
    name: 'Eco Latex',
    subtitle: '100% Organic Latex Core',
    type: 'Latex',
    category: 'latex',
    firmness: 'Medium Firm',
    thickness: '6 Inch',
    thickness_cm: 15,
    sqftPrice: 600,
    warranty: 7,
    warranty_years: 7,
    priceValue: 10800,
    price: '₹10,800',
    originalPrice: 14040,
    rating: 4.8,
    reviews: 1240,
    badge: 'NEW',
    badgeColor: 'bg-[#7cb93e] text-white',
    description: '100% Organic Latex Core offering advanced spine support, pressure relief, and eco-friendly natural materials.',
    benefits: ['Advanced spine support', 'Pressure relief', 'Eco-friendly materials'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309272/file_jwuqkf.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309272/file_jwuqkf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309272/file_jwuqkf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309272/file_jwuqkf.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 15, price: 10800, mrp: 14040, stock: 15, sku: 'ECO-6-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'ecolatex-6',
        priceValue: 10800,
        price: '₹10,800',
        originalPrice: 14040,
        sqftPrice: 600,
        warranty: 7,
        warranty_years: 7,
        badge: 'NEW',
        badgeColor: 'bg-[#7cb93e] text-white',
        subtitle: '100% Organic Latex Core',
        description: '100% Organic Latex Core offering advanced spine support, pressure relief, and eco-friendly natural materials.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309272/file_jwuqkf.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309272/file_jwuqkf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309272/file_jwuqkf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309272/file_jwuqkf.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'ecolatex-8',
        priceValue: 19008,
        price: '₹19,008',
        originalPrice: 24710,
        sqftPrice: 1056,
        warranty: 10,
        warranty_years: 10,
        badge: 'BEST SELLER',
        badgeColor: 'bg-[#3b82f6] text-white',
        subtitle: '100% Organic Latex Core',
        description: 'Deep 8-inch organic latex core providing superior orthopedic alignment and zero chemical emissions.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309270/file_ljyz2d.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309270/file_ljyz2d.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309270/file_ljyz2d.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309270/file_ljyz2d.png'],
      },
    ],
  },
  {
    id: 3,
    slug: 'ecolatex-8',
    title: 'Eco Latex',
    name: 'Eco Latex',
    subtitle: '100% Organic Latex Core',
    type: 'Latex',
    category: 'latex',
    firmness: 'Medium Firm',
    thickness: '8 Inch',
    thickness_cm: 20,
    sqftPrice: 1056,
    warranty: 10,
    warranty_years: 10,
    priceValue: 19008,
    price: '₹19,008',
    originalPrice: 24710,
    rating: 4.9,
    reviews: 1100,
    badge: 'BEST SELLER',
    badgeColor: 'bg-[#3b82f6] text-white',
    description: 'Deep 8-inch organic latex core providing superior orthopedic alignment and zero chemical emissions.',
    benefits: ['Pure Organic Latex', 'Hypoallergenic & Antimicrobial', 'Deep Orthopaedic Support'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309270/file_ljyz2d.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309270/file_ljyz2d.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309270/file_ljyz2d.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309270/file_ljyz2d.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 20, price: 19008, mrp: 24710, stock: 12, sku: 'ECO-8-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'ecolatex-6',
        priceValue: 10800,
        price: '₹10,800',
        originalPrice: 14040,
        sqftPrice: 600,
        warranty: 7,
        warranty_years: 7,
        badge: 'NEW',
        badgeColor: 'bg-[#7cb93e] text-white',
        subtitle: '100% Organic Latex Core',
        description: '100% Organic Latex Core offering advanced spine support, pressure relief, and eco-friendly natural materials.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309272/file_jwuqkf.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309272/file_jwuqkf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309272/file_jwuqkf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309272/file_jwuqkf.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'ecolatex-8',
        priceValue: 19008,
        price: '₹19,008',
        originalPrice: 24710,
        sqftPrice: 1056,
        warranty: 10,
        warranty_years: 10,
        badge: 'BEST SELLER',
        badgeColor: 'bg-[#3b82f6] text-white',
        subtitle: '100% Organic Latex Core',
        description: 'Deep 8-inch organic latex core providing superior orthopedic alignment and zero chemical emissions.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309270/file_ljyz2d.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309270/file_ljyz2d.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309270/file_ljyz2d.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309270/file_ljyz2d.png'],
      },
    ],
  },
  {
    id: 4,
    slug: 'luxoria',
    title: 'Luxoria',
    name: 'Luxoria',
    subtitle: 'Luxury HR Pocket Spring',
    type: 'Hybrid',
    category: 'hybrid',
    firmness: 'Soft',
    thickness: '8 Inch',
    thickness_cm: 20,
    sqftPrice: 720,
    warranty: 10,
    warranty_years: 10,
    priceValue: 12960,
    price: '₹12,960',
    originalPrice: 16848,
    rating: 4.9,
    reviews: 850,
    badge: 'LUXURY',
    badgeColor: 'bg-[#0B1A2A] text-white',
    description: 'Crafted with premium pocket springs and HR foam to deliver exceptional hotel comfort and zero motion transfer.',
    benefits: ['Cloud-like comfort', 'Independent Pocket Springs', 'Zero Partner Disturbance'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309269/file_eyfbz8.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309269/file_eyfbz8.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309269/file_eyfbz8.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309269/file_eyfbz8.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 20, price: 12960, mrp: 16848, stock: 10, sku: 'LUX-8-S' }],
    status: 'active'
  },
  {
    id: 5,
    slug: 'memory-dump-6',
    title: 'Memory Dump',
    name: 'Memory Dump',
    subtitle: 'Cooling Gel Memory Foam',
    type: 'Orthopaedic',
    category: 'orthopaedic',
    firmness: 'Soft',
    thickness: '6 Inch',
    thickness_cm: 15,
    sqftPrice: 630,
    warranty: 10,
    warranty_years: 10,
    priceValue: 11340,
    price: '₹11,340',
    originalPrice: 14742,
    rating: 4.8,
    reviews: 950,
    badge: 'NEW',
    badgeColor: 'bg-[#7cb93e] text-white',
    description: 'Cooling Gel Memory Foam offering cloud-like comfort that contours to your body shape and relieves pressure points.',
    benefits: ['Cloud-like comfort', 'Pressure relief', 'Cooling Gel Memory Foam'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 15, price: 11340, mrp: 14742, stock: 15, sku: 'MEMD-6-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'memory-dump-6',
        priceValue: 11340,
        price: '₹11,340',
        originalPrice: 14742,
        sqftPrice: 630,
        warranty: 10,
        warranty_years: 10,
        badge: 'NEW',
        badgeColor: 'bg-[#7cb93e] text-white',
        subtitle: 'Cooling Gel Memory Foam',
        description: 'Cooling Gel Memory Foam offering cloud-like comfort that contours to your body shape and relieves pressure points.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'memory-dump-8',
        priceValue: 15840,
        price: '₹15,840',
        originalPrice: 20592,
        sqftPrice: 880,
        warranty: 10,
        warranty_years: 10,
        badge: 'POPULAR',
        badgeColor: 'bg-[#8b5cf6] text-white',
        subtitle: 'Cooling Gel Memory Foam',
        description: 'Enhanced 8-inch cooling gel memory foam for deeper contouring and luxurious pressure relief.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png'],
      },
      {
        thickness: '10 Inch',
        thickness_cm: 25,
        slug: 'memory-dump-10',
        priceValue: 21600,
        price: '₹21,600',
        originalPrice: 28080,
        sqftPrice: 1200,
        warranty: 10,
        warranty_years: 10,
        badge: 'ULTRA PLUSH',
        badgeColor: 'bg-[#ec4899] text-white',
        subtitle: 'Ultra Plush Memory Foam',
        description: 'Ultimate 10-inch luxury memory foam mattress engineered for zero partner disturbance and supreme sleep comfort.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png'],
      },
    ],
  },
  {
    id: 6,
    slug: 'memory-dump-8',
    title: 'Memory Dump',
    name: 'Memory Dump',
    subtitle: 'Cooling Gel Memory Foam',
    type: 'Orthopaedic',
    category: 'orthopaedic',
    firmness: 'Soft',
    thickness: '8 Inch',
    thickness_cm: 20,
    sqftPrice: 880,
    warranty: 10,
    warranty_years: 10,
    priceValue: 15840,
    price: '₹15,840',
    originalPrice: 20592,
    rating: 4.9,
    reviews: 820,
    badge: 'POPULAR',
    badgeColor: 'bg-[#8b5cf6] text-white',
    description: 'Enhanced 8-inch cooling gel memory foam for deeper contouring and luxurious pressure relief.',
    benefits: ['Deep Contour Cushioning', 'Pressure relief', 'Cooling Gel Memory Foam'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 20, price: 15840, mrp: 20592, stock: 12, sku: 'MEMD-8-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'memory-dump-6',
        priceValue: 11340,
        price: '₹11,340',
        originalPrice: 14742,
        sqftPrice: 630,
        warranty: 10,
        warranty_years: 10,
        badge: 'NEW',
        badgeColor: 'bg-[#7cb93e] text-white',
        subtitle: 'Cooling Gel Memory Foam',
        description: 'Cooling Gel Memory Foam offering cloud-like comfort that contours to your body shape and relieves pressure points.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'memory-dump-8',
        priceValue: 15840,
        price: '₹15,840',
        originalPrice: 20592,
        sqftPrice: 880,
        warranty: 10,
        warranty_years: 10,
        badge: 'POPULAR',
        badgeColor: 'bg-[#8b5cf6] text-white',
        subtitle: 'Cooling Gel Memory Foam',
        description: 'Enhanced 8-inch cooling gel memory foam for deeper contouring and luxurious pressure relief.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png'],
      },
      {
        thickness: '10 Inch',
        thickness_cm: 25,
        slug: 'memory-dump-10',
        priceValue: 21600,
        price: '₹21,600',
        originalPrice: 28080,
        sqftPrice: 1200,
        warranty: 10,
        warranty_years: 10,
        badge: 'ULTRA PLUSH',
        badgeColor: 'bg-[#ec4899] text-white',
        subtitle: 'Ultra Plush Memory Foam',
        description: 'Ultimate 10-inch luxury memory foam mattress engineered for zero partner disturbance and supreme sleep comfort.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png'],
      },
    ],
  },
  {
    id: 7,
    slug: 'memory-dump-10',
    title: 'Memory Dump',
    name: 'Memory Dump',
    subtitle: 'Ultra Plush Memory Foam',
    type: 'Orthopaedic',
    category: 'orthopaedic',
    firmness: 'Soft',
    thickness: '10 Inch',
    thickness_cm: 25,
    sqftPrice: 1200,
    warranty: 10,
    warranty_years: 10,
    priceValue: 21600,
    price: '₹21,600',
    originalPrice: 28080,
    rating: 4.9,
    reviews: 640,
    badge: 'ULTRA PLUSH',
    badgeColor: 'bg-[#ec4899] text-white',
    description: 'Ultimate 10-inch luxury memory foam mattress engineered for zero partner disturbance and supreme sleep comfort.',
    benefits: ['Supreme 10-inch Plush Feel', 'Zero Motion Transfer', 'Advanced Temperature Regulation'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 25, price: 21600, mrp: 28080, stock: 8, sku: 'MEMD-10-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'memory-dump-6',
        priceValue: 11340,
        price: '₹11,340',
        originalPrice: 14742,
        sqftPrice: 630,
        warranty: 10,
        warranty_years: 10,
        badge: 'NEW',
        badgeColor: 'bg-[#7cb93e] text-white',
        subtitle: 'Cooling Gel Memory Foam',
        description: 'Cooling Gel Memory Foam offering cloud-like comfort that contours to your body shape and relieves pressure points.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309275/file_xsycn1.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'memory-dump-8',
        priceValue: 15840,
        price: '₹15,840',
        originalPrice: 20592,
        sqftPrice: 880,
        warranty: 10,
        warranty_years: 10,
        badge: 'POPULAR',
        badgeColor: 'bg-[#8b5cf6] text-white',
        subtitle: 'Cooling Gel Memory Foam',
        description: 'Enhanced 8-inch cooling gel memory foam for deeper contouring and luxurious pressure relief.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309278/file_gvsmkx.png'],
      },
      {
        thickness: '10 Inch',
        thickness_cm: 25,
        slug: 'memory-dump-10',
        priceValue: 21600,
        price: '₹21,600',
        originalPrice: 28080,
        sqftPrice: 1200,
        warranty: 10,
        warranty_years: 10,
        badge: 'ULTRA PLUSH',
        badgeColor: 'bg-[#ec4899] text-white',
        subtitle: 'Ultra Plush Memory Foam',
        description: 'Ultimate 10-inch luxury memory foam mattress engineered for zero partner disturbance and supreme sleep comfort.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309267/file_wzfsp5.png'],
      },
    ],
  },
  {
    id: 8,
    slug: 'mona-lite',
    title: 'Mona Lite',
    name: 'Mona Lite',
    subtitle: 'Comfort Budget Mattress',
    type: 'Budget Mattress',
    category: 'budget',
    firmness: 'Firm',
    thickness: '5 Inch',
    thickness_cm: 12,
    sqftPrice: 368,
    warranty: 5,
    warranty_years: 5,
    priceValue: 6624,
    price: '₹6,624',
    originalPrice: 8611,
    rating: 4.6,
    reviews: 1450,
    badge: 'VALUE',
    badgeColor: 'bg-[#f59e0b] text-white',
    description: 'Quality sleep at an unbeatable price point with durable orthopedic foam support and breathable fabric.',
    benefits: ['Unbeatable Value', 'Durable Foam Core', 'Breathable Fabric'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309235/file_i8ln3k.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309235/file_i8ln3k.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309235/file_i8ln3k.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309235/file_i8ln3k.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 12, price: 6624, mrp: 8611, stock: 25, sku: 'MONL-5-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '5 Inch',
        thickness_cm: 12,
        slug: 'mona-lite',
        priceValue: 6624,
        price: '₹6,624',
        originalPrice: 8611,
        sqftPrice: 368,
        warranty: 5,
        warranty_years: 5,
        badge: 'VALUE',
        badgeColor: 'bg-[#f59e0b] text-white',
        subtitle: 'Comfort Budget Mattress',
        description: 'Quality sleep at an unbeatable price point with durable orthopedic foam support and breathable fabric.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309235/file_i8ln3k.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309235/file_i8ln3k.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309235/file_i8ln3k.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309235/file_i8ln3k.png'],
      },
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'mona-lite-6',
        priceValue: 7938,
        price: '₹7,938',
        originalPrice: 10319,
        sqftPrice: 441,
        warranty: 5,
        warranty_years: 5,
        badge: 'VALUE',
        badgeColor: 'bg-[#f59e0b] text-white',
        subtitle: 'Comfort Budget Mattress',
        description: 'Extra 6-inch cushioning and durable orthopaedic foam support designed for daily budget-friendly comfort.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309237/file_uepcd2.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309237/file_uepcd2.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309237/file_uepcd2.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309237/file_uepcd2.png'],
      },
    ],
  },
  {
    id: 9,
    slug: 'mona-lite-6',
    title: 'Mona Lite',
    name: 'Mona Lite',
    subtitle: 'Comfort Budget Mattress',
    type: 'Budget Mattress',
    category: 'budget',
    firmness: 'Firm',
    thickness: '6 Inch',
    thickness_cm: 15,
    sqftPrice: 441,
    warranty: 5,
    warranty_years: 5,
    priceValue: 7938,
    price: '₹7,938',
    originalPrice: 10319,
    rating: 4.7,
    reviews: 1120,
    badge: 'VALUE',
    badgeColor: 'bg-[#f59e0b] text-white',
    description: 'Extra 6-inch cushioning and durable orthopaedic foam support designed for daily budget-friendly comfort.',
    benefits: ['Enhanced Cushioning', 'Durable Foam Core', 'Great Value'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309237/file_uepcd2.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309237/file_uepcd2.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309237/file_uepcd2.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309237/file_uepcd2.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 15, price: 7938, mrp: 10319, stock: 20, sku: 'MONL-6-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '5 Inch',
        thickness_cm: 12,
        slug: 'mona-lite',
        priceValue: 6624,
        price: '₹6,624',
        originalPrice: 8611,
        sqftPrice: 368,
        warranty: 5,
        warranty_years: 5,
        badge: 'VALUE',
        badgeColor: 'bg-[#f59e0b] text-white',
        subtitle: 'Comfort Budget Mattress',
        description: 'Quality sleep at an unbeatable price point with durable orthopedic foam support and breathable fabric.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309235/file_i8ln3k.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309235/file_i8ln3k.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309235/file_i8ln3k.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309235/file_i8ln3k.png'],
      },
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'mona-lite-6',
        priceValue: 7938,
        price: '₹7,938',
        originalPrice: 10319,
        sqftPrice: 441,
        warranty: 5,
        warranty_years: 5,
        badge: 'VALUE',
        badgeColor: 'bg-[#f59e0b] text-white',
        subtitle: 'Comfort Budget Mattress',
        description: 'Extra 6-inch cushioning and durable orthopaedic foam support designed for daily budget-friendly comfort.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309237/file_uepcd2.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309237/file_uepcd2.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309237/file_uepcd2.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309237/file_uepcd2.png'],
      },
    ],
  },
  {
    id: 10,
    slug: 'luxoria-latex',
    title: 'Luxoria Latex',
    name: 'Luxoria Latex',
    subtitle: 'Luxury HR & Natural Latex Hybrid',
    type: 'Hybrid',
    category: 'hybrid',
    firmness: 'Soft',
    thickness: '8 Inch',
    thickness_cm: 20,
    sqftPrice: 1215,
    warranty: 10,
    warranty_years: 10,
    priceValue: 21870,
    price: '₹21,870',
    originalPrice: 28431,
    rating: 4.9,
    reviews: 920,
    badge: 'LUXURY',
    badgeColor: 'bg-[#0B1A2A] text-white',
    description: 'Experience luxury with 100% natural latex and pocket springs for ultimate comfort and spinal alignment.',
    benefits: ['100% Natural Latex', 'Pocket Spring Core', 'Zero Partner Disturbance'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309241/file_wdvv4q.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309241/file_wdvv4q.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309241/file_wdvv4q.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309241/file_wdvv4q.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 20, price: 21870, mrp: 28431, stock: 10, sku: 'LUXL-8-S' }],
    status: 'active'
  },
  {
    id: 11,
    slug: 'natural-latex-4',
    title: 'Natural Latex',
    name: 'Natural Latex',
    subtitle: '100% Pure Organic Latex Core',
    type: 'Latex',
    category: 'latex',
    firmness: 'Medium Soft',
    thickness: '4 Inch',
    thickness_cm: 10,
    sqftPrice: 750,
    warranty: 10,
    warranty_years: 10,
    priceValue: 13500,
    price: '₹13,500',
    originalPrice: 17550,
    rating: 4.8,
    reviews: 740,
    badge: 'ORGANIC',
    badgeColor: 'bg-[#10b981] text-white',
    description: '100% Pure Organic Latex Core providing zero chemical emissions, antimicrobial protection, and responsive support.',
    benefits: ['Pure Organic Latex', 'Hypoallergenic & Antimicrobial', 'Zero Chemical Emissions'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 10, price: 13500, mrp: 17550, stock: 15, sku: 'NATL-4-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '4 Inch',
        thickness_cm: 10,
        slug: 'natural-latex-4',
        priceValue: 13500,
        price: '₹13,500',
        originalPrice: 17550,
        sqftPrice: 750,
        warranty: 10,
        warranty_years: 10,
        badge: 'ORGANIC',
        badgeColor: 'bg-[#10b981] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: '100% Pure Organic Latex Core providing zero chemical emissions, antimicrobial protection, and responsive support.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png'],
      },
      {
        thickness: '5 Inch',
        thickness_cm: 12,
        slug: 'natural-latex-5',
        priceValue: 16740,
        price: '₹16,740',
        originalPrice: 21762,
        sqftPrice: 930,
        warranty: 10,
        warranty_years: 10,
        badge: 'ORGANIC',
        badgeColor: 'bg-[#10b981] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: '5-inch pure organic natural latex mattress with pin-core ventilation for a naturally cool, pressure-relieving sleep.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png'],
      },
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'natural-latex',
        priceValue: 19260,
        price: '₹19,260',
        originalPrice: 25038,
        sqftPrice: 1070,
        warranty: 10,
        warranty_years: 10,
        badge: 'BEST SELLER',
        badgeColor: 'bg-[#3b82f6] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: 'Our best-selling 6-inch pure natural latex core offering optimal spinal alignment and long-lasting eco-friendly comfort.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'natural-latex-8',
        priceValue: 25380,
        price: '₹25,380',
        originalPrice: 32994,
        sqftPrice: 1410,
        warranty: 10,
        warranty_years: 10,
        badge: 'PREMIUM',
        badgeColor: 'bg-[#059669] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: 'Deep 8-inch 100% natural organic latex providing unmatched buoyancy, luxury cushioning, and lifetime durability.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png'],
      },
    ],
  },
  {
    id: 12,
    slug: 'natural-latex-5',
    title: 'Natural Latex',
    name: 'Natural Latex',
    subtitle: '100% Pure Organic Latex Core',
    type: 'Latex',
    category: 'latex',
    firmness: 'Medium Soft',
    thickness: '5 Inch',
    thickness_cm: 12,
    sqftPrice: 930,
    warranty: 10,
    warranty_years: 10,
    priceValue: 16740,
    price: '₹16,740',
    originalPrice: 21762,
    rating: 4.8,
    reviews: 810,
    badge: 'ORGANIC',
    badgeColor: 'bg-[#10b981] text-white',
    description: '5-inch pure organic natural latex mattress with pin-core ventilation for a naturally cool, pressure-relieving sleep.',
    benefits: ['Pure Organic Latex', 'Pin-core Ventilation', 'Hypoallergenic Protection'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 12, price: 16740, mrp: 21762, stock: 12, sku: 'NATL-5-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '4 Inch',
        thickness_cm: 10,
        slug: 'natural-latex-4',
        priceValue: 13500,
        price: '₹13,500',
        originalPrice: 17550,
        sqftPrice: 750,
        warranty: 10,
        warranty_years: 10,
        badge: 'ORGANIC',
        badgeColor: 'bg-[#10b981] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: '100% Pure Organic Latex Core providing zero chemical emissions, antimicrobial protection, and responsive support.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png'],
      },
      {
        thickness: '5 Inch',
        thickness_cm: 12,
        slug: 'natural-latex-5',
        priceValue: 16740,
        price: '₹16,740',
        originalPrice: 21762,
        sqftPrice: 930,
        warranty: 10,
        warranty_years: 10,
        badge: 'ORGANIC',
        badgeColor: 'bg-[#10b981] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: '5-inch pure organic natural latex mattress with pin-core ventilation for a naturally cool, pressure-relieving sleep.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png'],
      },
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'natural-latex',
        priceValue: 19260,
        price: '₹19,260',
        originalPrice: 25038,
        sqftPrice: 1070,
        warranty: 10,
        warranty_years: 10,
        badge: 'BEST SELLER',
        badgeColor: 'bg-[#3b82f6] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: 'Our best-selling 6-inch pure natural latex core offering optimal spinal alignment and long-lasting eco-friendly comfort.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'natural-latex-8',
        priceValue: 25380,
        price: '₹25,380',
        originalPrice: 32994,
        sqftPrice: 1410,
        warranty: 10,
        warranty_years: 10,
        badge: 'PREMIUM',
        badgeColor: 'bg-[#059669] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: 'Deep 8-inch 100% natural organic latex providing unmatched buoyancy, luxury cushioning, and lifetime durability.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png'],
      },
    ],
  },
  {
    id: 13,
    slug: 'natural-latex',
    title: 'Natural Latex',
    name: 'Natural Latex',
    subtitle: '100% Pure Organic Latex Core',
    type: 'Latex',
    category: 'latex',
    firmness: 'Medium Soft',
    thickness: '6 Inch',
    thickness_cm: 15,
    sqftPrice: 1070,
    warranty: 10,
    warranty_years: 10,
    priceValue: 19260,
    price: '₹19,260',
    originalPrice: 25038,
    rating: 4.9,
    reviews: 1280,
    badge: 'BEST SELLER',
    badgeColor: 'bg-[#3b82f6] text-white',
    description: 'Our best-selling 6-inch pure natural latex core offering optimal spinal alignment and long-lasting eco-friendly comfort.',
    benefits: ['Optimal Spinal Alignment', 'Pure Organic Latex', 'Pin-core Breathability'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 15, price: 19260, mrp: 25038, stock: 14, sku: 'NATL-6-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '4 Inch',
        thickness_cm: 10,
        slug: 'natural-latex-4',
        priceValue: 13500,
        price: '₹13,500',
        originalPrice: 17550,
        sqftPrice: 750,
        warranty: 10,
        warranty_years: 10,
        badge: 'ORGANIC',
        badgeColor: 'bg-[#10b981] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: '100% Pure Organic Latex Core providing zero chemical emissions, antimicrobial protection, and responsive support.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png'],
      },
      {
        thickness: '5 Inch',
        thickness_cm: 12,
        slug: 'natural-latex-5',
        priceValue: 16740,
        price: '₹16,740',
        originalPrice: 21762,
        sqftPrice: 930,
        warranty: 10,
        warranty_years: 10,
        badge: 'ORGANIC',
        badgeColor: 'bg-[#10b981] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: '5-inch pure organic natural latex mattress with pin-core ventilation for a naturally cool, pressure-relieving sleep.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png'],
      },
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'natural-latex',
        priceValue: 19260,
        price: '₹19,260',
        originalPrice: 25038,
        sqftPrice: 1070,
        warranty: 10,
        warranty_years: 10,
        badge: 'BEST SELLER',
        badgeColor: 'bg-[#3b82f6] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: 'Our best-selling 6-inch pure natural latex core offering optimal spinal alignment and long-lasting eco-friendly comfort.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'natural-latex-8',
        priceValue: 25380,
        price: '₹25,380',
        originalPrice: 32994,
        sqftPrice: 1410,
        warranty: 10,
        warranty_years: 10,
        badge: 'PREMIUM',
        badgeColor: 'bg-[#059669] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: 'Deep 8-inch 100% natural organic latex providing unmatched buoyancy, luxury cushioning, and lifetime durability.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png'],
      },
    ],
  },
  {
    id: 14,
    slug: 'natural-latex-8',
    title: 'Natural Latex',
    name: 'Natural Latex',
    subtitle: '100% Pure Organic Latex Core',
    type: 'Latex',
    category: 'latex',
    firmness: 'Medium Soft',
    thickness: '8 Inch',
    thickness_cm: 20,
    sqftPrice: 1410,
    warranty: 10,
    warranty_years: 10,
    priceValue: 25380,
    price: '₹25,380',
    originalPrice: 32994,
    rating: 4.9,
    reviews: 950,
    badge: 'PREMIUM',
    badgeColor: 'bg-[#059669] text-white',
    description: 'Deep 8-inch 100% natural organic latex providing unmatched buoyancy, luxury cushioning, and lifetime durability.',
    benefits: ['Deep Luxury Cushioning', 'Pure Organic Latex', 'Lifetime Durability'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 20, price: 25380, mrp: 32994, stock: 10, sku: 'NATL-8-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '4 Inch',
        thickness_cm: 10,
        slug: 'natural-latex-4',
        priceValue: 13500,
        price: '₹13,500',
        originalPrice: 17550,
        sqftPrice: 750,
        warranty: 10,
        warranty_years: 10,
        badge: 'ORGANIC',
        badgeColor: 'bg-[#10b981] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: '100% Pure Organic Latex Core providing zero chemical emissions, antimicrobial protection, and responsive support.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309261/file_inlqbf.png'],
      },
      {
        thickness: '5 Inch',
        thickness_cm: 12,
        slug: 'natural-latex-5',
        priceValue: 16740,
        price: '₹16,740',
        originalPrice: 21762,
        sqftPrice: 930,
        warranty: 10,
        warranty_years: 10,
        badge: 'ORGANIC',
        badgeColor: 'bg-[#10b981] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: '5-inch pure organic natural latex mattress with pin-core ventilation for a naturally cool, pressure-relieving sleep.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309247/file_yzpmdh.png'],
      },
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'natural-latex',
        priceValue: 19260,
        price: '₹19,260',
        originalPrice: 25038,
        sqftPrice: 1070,
        warranty: 10,
        warranty_years: 10,
        badge: 'BEST SELLER',
        badgeColor: 'bg-[#3b82f6] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: 'Our best-selling 6-inch pure natural latex core offering optimal spinal alignment and long-lasting eco-friendly comfort.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309265/file_ivsmr0.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'natural-latex-8',
        priceValue: 25380,
        price: '₹25,380',
        originalPrice: 32994,
        sqftPrice: 1410,
        warranty: 10,
        warranty_years: 10,
        badge: 'PREMIUM',
        badgeColor: 'bg-[#059669] text-white',
        subtitle: '100% Pure Organic Latex Core',
        description: 'Deep 8-inch 100% natural organic latex providing unmatched buoyancy, luxury cushioning, and lifetime durability.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309244/file_sxb9rh.png'],
      },
    ],
  },
  {
    id: 15,
    slug: 'softy-bond',
    title: 'Softy Bond',
    name: 'Softy Bond',
    subtitle: 'Orthopaedic Bonded Mattress',
    type: 'Bonded Series',
    category: 'bonded',
    firmness: 'Medium Firm',
    thickness: '6 Inch',
    thickness_cm: 15,
    sqftPrice: 580,
    warranty: 10,
    warranty_years: 10,
    priceValue: 10440,
    price: '₹10,440',
    originalPrice: 13572,
    rating: 4.7,
    reviews: 920,
    badge: 'NEW',
    badgeColor: 'bg-[#3b82f6] text-white',
    description: 'Orthopaedic Bonded Mattress engineered with High-Density Bonded Foam for strong spine alignment and soft top feel.',
    benefits: ['Orthopaedic alignment', 'Plush comfort layer', 'Zero Partner Disturbance'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 15, price: 10440, mrp: 13572, stock: 15, sku: 'SOFTB-6-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'softy-bond',
        priceValue: 10440,
        price: '₹10,440',
        originalPrice: 13572,
        sqftPrice: 580,
        warranty: 10,
        warranty_years: 10,
        badge: 'NEW',
        badgeColor: 'bg-[#3b82f6] text-white',
        subtitle: 'Orthopaedic Bonded Mattress',
        description: 'Orthopaedic Bonded Mattress engineered with High-Density Bonded Foam for strong spine alignment and soft top feel.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'softy-bond-plus',
        priceValue: 14166,
        price: '₹14,166',
        originalPrice: 18416,
        sqftPrice: 787,
        warranty: 10,
        warranty_years: 10,
        badge: 'EXCLUSIVE',
        badgeColor: 'bg-[#ef4444] text-white',
        subtitle: 'Premium Bonded Ortho Support',
        description: 'Premium 8-inch bonded ortho support with superior weight distribution and orthopaedic support for long-lasting durability.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png'],
      },
    ],
  },
  {
    id: 16,
    slug: 'softy-bond-plus',
    title: 'Softy Bond',
    name: 'Softy Bond',
    subtitle: 'Premium Bonded Ortho Support',
    type: 'Bonded Series',
    category: 'bonded',
    firmness: 'Medium Firm',
    thickness: '8 Inch',
    thickness_cm: 20,
    sqftPrice: 787,
    warranty: 10,
    warranty_years: 10,
    priceValue: 14166,
    price: '₹14,166',
    originalPrice: 18416,
    rating: 4.9,
    reviews: 1120,
    badge: 'EXCLUSIVE',
    badgeColor: 'bg-[#ef4444] text-white',
    description: 'Premium 8-inch bonded ortho support with superior weight distribution and orthopaedic support for long-lasting durability.',
    benefits: ['Enhanced orthopaedic support', 'Deep plush feel', 'Heavy Weight Support'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 20, price: 14166, mrp: 18416, stock: 10, sku: 'SOFTBP-8-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'softy-bond',
        priceValue: 10440,
        price: '₹10,440',
        originalPrice: 13572,
        sqftPrice: 580,
        warranty: 10,
        warranty_years: 10,
        badge: 'NEW',
        badgeColor: 'bg-[#3b82f6] text-white',
        subtitle: 'Orthopaedic Bonded Mattress',
        description: 'Orthopaedic Bonded Mattress engineered with High-Density Bonded Foam for strong spine alignment and soft top feel.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'softy-bond-plus',
        priceValue: 14166,
        price: '₹14,166',
        originalPrice: 18416,
        sqftPrice: 787,
        warranty: 10,
        warranty_years: 10,
        badge: 'EXCLUSIVE',
        badgeColor: 'bg-[#ef4444] text-white',
        subtitle: 'Premium Bonded Ortho Support',
        description: 'Premium 8-inch bonded ortho support with superior weight distribution and orthopaedic support for long-lasting durability.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309250/file_tiitcm.png'],
      },
    ],
  },
  {
    id: 17,
    slug: 'memory-bond',
    title: 'Memory Bond',
    name: 'Memory Bond',
    subtitle: 'Bonded Core & Plush Memory Top',
    type: 'Orthopaedic',
    category: 'orthopaedic',
    firmness: 'Medium Soft',
    thickness: '6 Inch',
    thickness_cm: 15,
    sqftPrice: 800,
    warranty: 10,
    warranty_years: 10,
    priceValue: 14400,
    price: '₹14,400',
    originalPrice: 18720,
    rating: 4.8,
    reviews: 1540,
    badge: 'PREMIUM',
    badgeColor: 'bg-[#10b981] text-white',
    description: 'Bonded Core & Plush Memory Top specially designed for heavy weight sleepers above 80 kg with cloud-like memory contour.',
    benefits: ['Adapts to body shape', 'Relieves pressure points', 'Heavy Weight Support above 80 kg'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 15, price: 14400, mrp: 18720, stock: 15, sku: 'MEMB-6-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'memory-bond',
        priceValue: 14400,
        price: '₹14,400',
        originalPrice: 18720,
        sqftPrice: 800,
        warranty: 10,
        warranty_years: 10,
        badge: 'PREMIUM',
        badgeColor: 'bg-[#10b981] text-white',
        subtitle: 'Bonded Core & Plush Memory Top',
        description: 'Bonded Core & Plush Memory Top specially designed for heavy weight sleepers above 80 kg with cloud-like memory contour.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'memory-bond-plus',
        priceValue: 18810,
        price: '₹18,810',
        originalPrice: 24453,
        sqftPrice: 1045,
        warranty: 10,
        warranty_years: 10,
        badge: 'EXCLUSIVE',
        badgeColor: 'bg-[#ef4444] text-white',
        subtitle: 'Enhanced Memory Contour & Bonded Core',
        description: 'Enhanced Memory Contour & 8-inch Bonded Core for long-lasting comfort combined with high-density support.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png'],
      },
    ],
  },
  {
    id: 18,
    slug: 'memory-bond-plus',
    title: 'Memory Bond',
    name: 'Memory Bond',
    subtitle: 'Enhanced Memory Contour & Bonded Core',
    type: 'Orthopaedic',
    category: 'orthopaedic',
    firmness: 'Medium Soft',
    thickness: '8 Inch',
    thickness_cm: 20,
    sqftPrice: 1045,
    warranty: 10,
    warranty_years: 10,
    priceValue: 18810,
    price: '₹18,810',
    originalPrice: 24453,
    rating: 4.9,
    reviews: 1240,
    badge: 'EXCLUSIVE',
    badgeColor: 'bg-[#ef4444] text-white',
    description: 'Enhanced Memory Contour & 8-inch Bonded Core for long-lasting comfort combined with high-density support.',
    benefits: ['Deep Plush Memory Top', 'Heavy Weight Ortho Support', 'Zero Partner Disturbance'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 20, price: 18810, mrp: 24453, stock: 10, sku: 'MEMBP-8-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'memory-bond',
        priceValue: 14400,
        price: '₹14,400',
        originalPrice: 18720,
        sqftPrice: 800,
        warranty: 10,
        warranty_years: 10,
        badge: 'PREMIUM',
        badgeColor: 'bg-[#10b981] text-white',
        subtitle: 'Bonded Core & Plush Memory Top',
        description: 'Bonded Core & Plush Memory Top specially designed for heavy weight sleepers above 80 kg with cloud-like memory contour.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'memory-bond-plus',
        priceValue: 18810,
        price: '₹18,810',
        originalPrice: 24453,
        sqftPrice: 1045,
        warranty: 10,
        warranty_years: 10,
        badge: 'EXCLUSIVE',
        badgeColor: 'bg-[#ef4444] text-white',
        subtitle: 'Enhanced Memory Contour & Bonded Core',
        description: 'Enhanced Memory Contour & 8-inch Bonded Core for long-lasting comfort combined with high-density support.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309254/file_p5umkd.png'],
      },
    ],
  },
  {
    id: 19,
    slug: 'lax-o-bond-6',
    title: 'Lax-o-Bond',
    name: 'Lax-o-Bond',
    subtitle: 'High-Density Bonded Foam',
    type: 'Orthopaedic',
    category: 'orthopaedic',
    firmness: 'Medium Soft',
    thickness: '6 Inch',
    thickness_cm: 15,
    sqftPrice: 810,
    warranty: 10,
    warranty_years: 10,
    priceValue: 14580,
    price: '₹14,580',
    originalPrice: 18954,
    rating: 4.7,
    reviews: 980,
    badge: 'POPULAR',
    badgeColor: 'bg-[#8b5cf6] text-white',
    description: 'High-Density Bonded Foam specially designed for individuals weighing above 80 kg with strong & durable support.',
    benefits: ['Strong & Durable Support', 'Excellent Weight Distribution', 'Orthopaedic Back Support', 'Heavy Weight Sleeper Ideal'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309262/file_nr0lxc.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309262/file_nr0lxc.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309262/file_nr0lxc.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309262/file_nr0lxc.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 15, price: 14580, mrp: 18954, stock: 15, sku: 'LAXB-6-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'lax-o-bond-6',
        priceValue: 14580,
        price: '₹14,580',
        originalPrice: 18954,
        sqftPrice: 810,
        warranty: 10,
        warranty_years: 10,
        badge: 'POPULAR',
        badgeColor: 'bg-[#8b5cf6] text-white',
        subtitle: 'High-Density Bonded Foam',
        description: 'High-Density Bonded Foam specially designed for individuals weighing above 80 kg with strong & durable support.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309262/file_nr0lxc.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309262/file_nr0lxc.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309262/file_nr0lxc.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309262/file_nr0lxc.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'lax-o-bond-8',
        priceValue: 18900,
        price: '₹18,900',
        originalPrice: 24570,
        sqftPrice: 1050,
        warranty: 10,
        warranty_years: 10,
        badge: 'HEAVY DUTY',
        badgeColor: 'bg-[#059669] text-white',
        subtitle: 'High-Density Bonded Foam',
        description: 'Extra deep 8-inch orthopaedic back support and excellent weight distribution for heavy weight sleepers.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309257/file_a6zpgy.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309257/file_a6zpgy.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309257/file_a6zpgy.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309257/file_a6zpgy.png'],
      },
    ],
  },
  {
    id: 20,
    slug: 'lax-o-bond-8',
    title: 'Lax-o-Bond',
    name: 'Lax-o-Bond',
    subtitle: 'High-Density Bonded Foam',
    type: 'Orthopaedic',
    category: 'orthopaedic',
    firmness: 'Medium Soft',
    thickness: '8 Inch',
    thickness_cm: 20,
    sqftPrice: 1050,
    warranty: 10,
    warranty_years: 10,
    priceValue: 18900,
    price: '₹18,900',
    originalPrice: 24570,
    rating: 4.8,
    reviews: 850,
    badge: 'HEAVY DUTY',
    badgeColor: 'bg-[#059669] text-white',
    description: 'Extra deep 8-inch orthopaedic back support and excellent weight distribution for heavy weight sleepers.',
    benefits: ['Strong & Durable Support', 'Excellent Weight Distribution', 'Orthopaedic Back Support', 'Long-Lasting Comfort'],
    image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309257/file_a6zpgy.png',
    images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309257/file_a6zpgy.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309257/file_a6zpgy.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309257/file_a6zpgy.png'],
    variants: [{ size: 'Single', dimensions: '72x36', thickness_cm: 20, price: 18900, mrp: 24570, stock: 12, sku: 'LAXB-8-S' }],
    status: 'active',
    thicknessVariants: [
      {
        thickness: '6 Inch',
        thickness_cm: 15,
        slug: 'lax-o-bond-6',
        priceValue: 14580,
        price: '₹14,580',
        originalPrice: 18954,
        sqftPrice: 810,
        warranty: 10,
        warranty_years: 10,
        badge: 'POPULAR',
        badgeColor: 'bg-[#8b5cf6] text-white',
        subtitle: 'High-Density Bonded Foam',
        description: 'High-Density Bonded Foam specially designed for individuals weighing above 80 kg with strong & durable support.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309262/file_nr0lxc.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309262/file_nr0lxc.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309262/file_nr0lxc.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309262/file_nr0lxc.png'],
      },
      {
        thickness: '8 Inch',
        thickness_cm: 20,
        slug: 'lax-o-bond-8',
        priceValue: 18900,
        price: '₹18,900',
        originalPrice: 24570,
        sqftPrice: 1050,
        warranty: 10,
        warranty_years: 10,
        badge: 'HEAVY DUTY',
        badgeColor: 'bg-[#059669] text-white',
        subtitle: 'High-Density Bonded Foam',
        description: 'Extra deep 8-inch orthopaedic back support and excellent weight distribution for heavy weight sleepers.',
        image: 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309257/file_a6zpgy.png',
        images: ['https://res.cloudinary.com/m1dy2af4/image/upload/v1785309257/file_a6zpgy.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309257/file_a6zpgy.png', 'https://res.cloudinary.com/m1dy2af4/image/upload/v1785309257/file_a6zpgy.png'],
      },
    ],
  },
];

export function getDeduplicatedCatalog(): CatalogProduct[] {
  const seen = new Set<string>();
  const list: CatalogProduct[] = [];
  
  for (const p of PRODUCT_CATALOG) {
    const cleanNameStr = p.name.replace(/\s*-\s*\d+\s*(inch|")?|\s+\d+\s*(inch|")?$/i, '').replace(/\s+plus$/i, '').trim();
    const baseName = cleanNameStr.toLowerCase();
    if (seen.has(baseName)) continue;
    seen.add(baseName);
    
    const thicknessDisplay = p.thicknessVariants && p.thicknessVariants.length > 1
      ? p.thicknessVariants.map(v => v.thickness.split(' ')[0] + '"').join(' / ')
      : p.thickness;
      
    list.push({
      ...p,
      title: cleanNameStr,
      thickness: thicknessDisplay
    });
  }

  const getMasterRank = (item: CatalogProduct) => {
    const t = (item.title || item.name || '').toLowerCase().trim();
    const s = (item.slug || '').toLowerCase().trim();
    if (t === 'mona lite' || s.includes('mona-lite')) return 1;
    if (t === 'mona softy' || s.includes('mona-softy')) return 2;
    if (t === 'eco latex' || s.includes('ecolatex')) return 3;
    if (t === 'luxoria' || s === 'luxoria') return 4;
    if (t === 'luxoria latex' || s.includes('luxoria-latex')) return 5;
    if (t === 'memory dump' || s.includes('memory-dump')) return 6;
    if (t === 'softy bond' || s.includes('softy-bond')) return 7;
    if (t === 'memory bond' || s.includes('memory-bond')) return 8;
    if (t === 'lax-o-bond' || s.includes('lax-o-bond')) return 9;
    if (t === 'natural latex' || s.includes('natural-latex')) return 10;
    return 99;
  };

  list.sort((a, b) => getMasterRank(a) - getMasterRank(b));
  return list;
}
